! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Hessian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ttropo_HessianSP.f90
! Time                 : Tue Dec  6 22:11:34 2016
! Working directory    : /home/tomas/ezkpp/test4
! Equation file        : ttropo.kpp
! Output root filename : ttropo
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ttropo_HessianSP

  PUBLIC
  SAVE


! Hessian Sparse Data
! 

  INTEGER, PARAMETER, DIMENSION(19) :: IHESS_I = (/ &
       1,  4,  5,  6,  9,  9,  9,  9, 10, 10, 10, 10, &
      11, 11, 11, 12, 12, 13, 13 /)

  INTEGER, PARAMETER, DIMENSION(19) :: IHESS_J = (/ &
       6,  9, 10,  6,  6,  9, 10, 10,  6, 10, 10, 10, &
       9, 10, 12, 10, 12, 10, 12 /)

  INTEGER, PARAMETER, DIMENSION(19) :: IHESS_K = (/ &
       9, 11, 10,  9,  9, 11, 12, 13,  9, 10, 12, 13, &
      11, 12, 13, 12, 13, 13, 13 /)


END MODULE ttropo_HessianSP

