! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ttropo_JacobianSP.f90
! Time                 : Wed Nov 30 11:03:15 2016
! Working directory    : /home/tomaschor/ezkpp/test4
! Equation file        : ttropo.kpp
! Output root filename : ttropo
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ttropo_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(48) :: LU_IROW = (/ &
       1,  1,  1,  2,  2,  3,  3,  4,  4,  4,  5,  5, &
       6,  6,  7,  7,  8,  8,  8,  8,  9,  9,  9,  9, &
       9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 11, 11, &
      11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13 /)

  INTEGER, PARAMETER, DIMENSION(48) :: LU_ICOL = (/ &
       1,  6,  9,  2,  5,  3,  4,  4,  9, 12,  5, 10, &
       6,  9,  7, 13,  7,  8, 12, 13,  5,  6,  7,  9, &
      10, 11, 12, 13,  6,  9, 10, 11, 12, 13, 10, 11, &
      12, 13,  9, 10, 11, 12, 13,  8, 10, 11, 12, 13 /)

  INTEGER, PARAMETER, DIMENSION(14) :: LU_CROW = (/ &
       1,  4,  6,  8, 11, 13, 15, 17, 21, 29, 35, 39, &
      44, 49 /)

  INTEGER, PARAMETER, DIMENSION(14) :: LU_DIAG = (/ &
       1,  4,  6,  8, 11, 13, 15, 18, 24, 31, 36, 42, &
      48, 49 /)


END MODULE ttropo_JacobianSP

