! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Hessian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ttropo_HessianSP.f90
! Time                 : Tue Nov 29 09:15:36 2016
! Working directory    : /home/tomas/ezkpp/test4
! Equation file        : ttropo.kpp
! Output root filename : ttropo
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ttropo_HessianSP

  PUBLIC
  SAVE


! Hessian Sparse Data
! 

  INTEGER, PARAMETER, DIMENSION(19) :: IHESS_I = (/ &
       1,  2,  3,  4,  7,  7,  7,  7,  8,  8,  9,  9, &
       9,  9, 10, 10, 11, 11, 11 /)

  INTEGER, PARAMETER, DIMENSION(19) :: IHESS_J = (/ &
       7,  4,  9,  4,  4,  7,  8,  9,  8,  8,  4,  8, &
       9,  9,  8,  9,  7,  8,  8 /)

  INTEGER, PARAMETER, DIMENSION(19) :: IHESS_K = (/ &
      11,  7,  9,  7,  7, 11,  9, 10,  9, 10,  7,  9, &
       9, 10, 10, 10, 11,  9, 10 /)


END MODULE ttropo_HessianSP

