! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ttropo_Monitor.f90
! Time                 : Tue Nov 29 13:15:32 2016
! Working directory    : /home/tomaschor/ezkpp/test4
! Equation file        : ttropo.kpp
! Output root filename : ttropo
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ttropo_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(14) :: SPC_NAMES = (/ &
     'H2O2           ','HNO3           ','CO2            ', &
     'O1D            ','O              ','NO2            ', &
     'NO             ','O3             ','M              ', &
     'O2             ','H2O            ','CO             ', &
     'OH             ','HO2            ' /)

  INTEGER, PARAMETER, DIMENSION(4) :: LOOKAT = (/ &
       6,  7,  8, 12 /)

  INTEGER, PARAMETER, DIMENSION(5) :: MONITOR = (/ &
       4,  5,  6,  7,  8 /)

  CHARACTER(LEN=15), PARAMETER, DIMENSION(1) :: SMASS = (/ &
     'N              ' /)

  CHARACTER(LEN=100), PARAMETER, DIMENSION(13) :: EQN_NAMES = (/ &
     '   O + O2 --> O3                                                                                    ', &
     '      NO2 --> O + NO                                                                                ', &
     '  NO + O3 --> NO2 + O2                                                                              ', &
     '       O3 --> O + O2                                                                                ', &
     '       O3 --> O1D + O2                                                                              ', &
     '  O1D + M --> O + M                                                                                 ', &
     'O1D + H2O --> 2 OH                                                                                  ', &
     '  CO + OH --> CO2 + HO2                                                                             ', &
     ' NO + HO2 --> NO2 + OH                                                                              ', &
     ' NO2 + OH --> HNO3                                                                                  ', &
     '    2 HO2 --> H2O2                                                                                  ', &
     ' O3 + HO2 --> 2 O2 + OH                                                                             ', &
     '     H2O2 --> 2 OH                                                                                  ' /)

! INLINED global variables

! End INLINED global variables


END MODULE ttropo_Monitor
