! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ttropo_JacobianSP.f90
! Time                 : Tue Dec  6 17:05:02 2016
! Working directory    : /home/tomas/ezkpp/test4
! Equation file        : ttropo.kpp
! Output root filename : ttropo
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ttropo_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(32) :: LU_IROW = (/ &
       1,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, &
       6,  7,  7,  7,  8,  8,  9,  9,  9,  9,  9,  9, &
      10, 10, 10, 10, 11, 11, 11, 11 /)

  INTEGER, PARAMETER, DIMENSION(32) :: LU_ICOL = (/ &
       1,  6,  9,  2,  5,  3,  4,  4,  9,  5, 10,  6, &
       9,  7,  8, 11,  8, 11,  5,  6,  8,  9, 10, 11, &
       6,  9, 10, 11,  7,  8, 10, 11 /)

  INTEGER, PARAMETER, DIMENSION(12) :: LU_CROW = (/ &
       1,  4,  6,  8, 10, 12, 14, 17, 19, 25, 29, 33 /)

  INTEGER, PARAMETER, DIMENSION(12) :: LU_DIAG = (/ &
       1,  4,  6,  8, 10, 12, 14, 17, 22, 27, 32, 33 /)


END MODULE ttropo_JacobianSP

