! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ttropo_Parameters.f90
! Time                 : Tue Nov 29 09:15:36 2016
! Working directory    : /home/tomas/ezkpp/test4
! Equation file        : ttropo.kpp
! Output root filename : ttropo
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ttropo_Parameters

  USE ttropo_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 14 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 11 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 9 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 3 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 13 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 12 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 42 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 44 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 12 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 14 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 19 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 6 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 5 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_HNO3 = 1 
  INTEGER, PARAMETER :: ind_CO2 = 2 
  INTEGER, PARAMETER :: ind_H2O2 = 3 
  INTEGER, PARAMETER :: ind_CO = 4 
  INTEGER, PARAMETER :: ind_O1D = 5 
  INTEGER, PARAMETER :: ind_O = 6 
  INTEGER, PARAMETER :: ind_OH = 7 
  INTEGER, PARAMETER :: ind_NO = 8 
  INTEGER, PARAMETER :: ind_HO2 = 9 
  INTEGER, PARAMETER :: ind_O3 = 10 
  INTEGER, PARAMETER :: ind_NO2 = 11 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_M = 12 
  INTEGER, PARAMETER :: ind_O2 = 13 
  INTEGER, PARAMETER :: ind_H2O = 14 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_M = 1 
  INTEGER, PARAMETER :: indf_O2 = 2 
  INTEGER, PARAMETER :: indf_H2O = 3 

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 18 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 34 

END MODULE ttropo_Parameters

