! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ttropo_Function.f90
! Time                 : Tue Nov 29 13:15:32 2016
! Working directory    : /home/tomaschor/ezkpp/test4
! Equation file        : ttropo.kpp
! Output root filename : ttropo
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ttropo_Function

  USE ttropo_Parameters
  IMPLICIT NONE

! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun - time derivatives of variables - Agregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)


! Computation of equation rates
  A(1) = RCT(1)*V(5)*F(2)
  A(2) = RCT(2)*V(6)
  A(3) = RCT(3)*V(7)*V(8)
  A(4) = RCT(4)*V(8)
  A(5) = RCT(5)*V(8)
  A(6) = RCT(6)*V(4)*F(1)
  A(7) = RCT(7)*V(4)*F(3)
  A(8) = RCT(8)*F(4)*F(5)
  A(9) = RCT(9)*V(7)*F(6)
  A(10) = RCT(10)*V(6)*F(5)
  A(11) = RCT(11)*F(6)*F(6)
  A(12) = RCT(12)*V(8)*F(6)
  A(13) = RCT(13)*V(1)

! Aggregate function
  Vdot(1) = A(11)-A(13)
  Vdot(2) = A(10)
  Vdot(3) = A(8)
  Vdot(4) = A(5)-A(6)-A(7)
  Vdot(5) = -A(1)+A(2)+A(4)+A(6)
  Vdot(6) = -A(2)+A(3)+A(9)-A(10)
  Vdot(7) = A(2)-A(3)-A(9)
  Vdot(8) = A(1)-A(3)-A(4)-A(5)-A(12)
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE ttropo_Function

