! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ttropo_JacobianSP.f90
! Time                 : Tue Nov 29 13:15:32 2016
! Working directory    : /home/tomaschor/ezkpp/test4
! Equation file        : ttropo.kpp
! Output root filename : ttropo
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ttropo_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(20) :: LU_IROW = (/ &
       1,  2,  2,  3,  4,  4,  5,  5,  5,  5,  6,  6, &
       6,  7,  7,  7,  8,  8,  8,  8 /)

  INTEGER, PARAMETER, DIMENSION(20) :: LU_ICOL = (/ &
       1,  2,  6,  3,  4,  8,  4,  5,  6,  8,  6,  7, &
       8,  6,  7,  8,  5,  6,  7,  8 /)

  INTEGER, PARAMETER, DIMENSION(9) :: LU_CROW = (/ &
       1,  2,  4,  5,  7, 11, 14, 17, 21 /)

  INTEGER, PARAMETER, DIMENSION(9) :: LU_DIAG = (/ &
       1,  2,  4,  5,  8, 11, 15, 20, 21 /)


END MODULE ttropo_JacobianSP

