! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Stoichiometric Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ttropo_StoichiomSP.f90
! Time                 : Tue Nov 29 13:15:32 2016
! Working directory    : /home/tomaschor/ezkpp/test4
! Equation file        : ttropo.kpp
! Output root filename : ttropo
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ttropo_StoichiomSP

  USE ttropo_Precision
  PUBLIC
  SAVE


! Row-compressed sparse data for the Jacobian of reaction products JVRP

  INTEGER, PARAMETER, DIMENSION(14) :: CROW_JVRP = (/ &
       1,  2,  3,  5,  6,  7,  8,  9,  9, 10, 11, 11, &
      12, 13 /)

  INTEGER, PARAMETER, DIMENSION(12) :: ICOL_JVRP = (/ &
       5,  6,  7,  8,  8,  8,  4,  4,  7,  6,  8,  1 /)

  INTEGER, PARAMETER, DIMENSION(12) :: IROW_JVRP = (/ &
       1,  2,  3,  3,  4,  5,  6,  7,  9, 10, 12, 13 /)



!  Stoichiometric Matrix in Compressed Column Sparse Format


  INTEGER, PARAMETER, DIMENSION(14) :: CCOL_STOICM = (/ &
       1,  3,  6,  9, 11, 13, 15, 16, 17, 19, 21, 22, &
      23, 24 /)

  INTEGER, PARAMETER, DIMENSION(23) :: IROW_STOICM = (/ &
       5,  8,  5,  6,  7,  6,  7,  8,  5,  8,  4,  8, &
       4,  5,  4,  3,  6,  7,  2,  6,  1,  8,  1 /)

  INTEGER, PARAMETER, DIMENSION(23) :: ICOL_STOICM = (/ &
       1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  5,  5, &
       6,  6,  7,  8,  9,  9, 10, 10, 11, 12, 13 /)

  REAL(kind=dp), PARAMETER, DIMENSION(23) :: STOICM = (/ &
       -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, &
       1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, &
       1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, &
       1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp /)


END MODULE ttropo_StoichiomSP

