! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Stoichiometric Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ttropo_StoichiomSP.f90
! Time                 : Tue Dec  6 17:05:02 2016
! Working directory    : /home/tomas/ezkpp/test4
! Equation file        : ttropo.kpp
! Output root filename : ttropo
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ttropo_StoichiomSP

  USE ttropo_Precision
  PUBLIC
  SAVE


! Row-compressed sparse data for the Jacobian of reaction products JVRP

  INTEGER, PARAMETER, DIMENSION(16) :: CROW_JVRP = (/ &
       1,  2,  2,  3,  4,  5,  6,  7,  9, 10, 11, 12, &
      14, 15, 16, 17 /)

  INTEGER, PARAMETER, DIMENSION(16) :: ICOL_JVRP = (/ &
       7, 11, 11, 11,  8,  8,  6,  9, 10,  9, 10, 10, &
      11,  5,  5,  4 /)

  INTEGER, PARAMETER, DIMENSION(16) :: IROW_JVRP = (/ &
       1,  3,  4,  5,  6,  7,  8,  8,  9, 10, 11, 12, &
      12, 13, 14, 15 /)



!  Stoichiometric Matrix in Compressed Column Sparse Format


  INTEGER, PARAMETER, DIMENSION(16) :: CCOL_STOICM = (/ &
       1,  3,  4,  5,  7,  9, 11, 13, 17, 19, 21, 23, &
      26, 28, 30, 32 /)

  INTEGER, PARAMETER, DIMENSION(31) :: IROW_STOICM = (/ &
       7, 11,  7, 11,  7, 11,  8, 11,  7,  8,  8,  9, &
       1,  6,  9, 10,  9, 10,  4,  9,  5, 10,  9, 10, &
      11,  5,  9,  2,  5,  3,  4 /)

  INTEGER, PARAMETER, DIMENSION(31) :: ICOL_STOICM = (/ &
       1,  1,  2,  3,  4,  4,  5,  5,  6,  6,  7,  7, &
       8,  8,  8,  8,  9,  9, 10, 10, 11, 11, 12, 12, &
      12, 13, 13, 14, 14, 15, 15 /)

  REAL(kind=dp), PARAMETER, DIMENSION(31) :: STOICM = (/ &
       -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, &
       -1.000000e+00_dp,  2.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp, &
       1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, &
       1.000000e+00_dp,  -2.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp, &
       -1.000000e+00_dp,  2.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       -1.000000e+00_dp /)


END MODULE ttropo_StoichiomSP

