! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ttropo_Monitor.f90
! Time                 : Wed Nov 30 11:03:15 2016
! Working directory    : /home/tomaschor/ezkpp/test4
! Equation file        : ttropo.kpp
! Output root filename : ttropo
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ttropo_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(16) :: SPC_NAMES = (/ &
     'CO2            ','H2O2aq         ','HNO3aq         ', &
     'HNO3           ','H2O2           ','CO             ', &
     'O1D            ','O              ','OH             ', &
     'HO2            ','NO             ','NO2            ', &
     'O3             ','M              ','O2             ', &
     'H2O            ' /)

  INTEGER, PARAMETER, DIMENSION(7) :: LOOKAT = (/ &
       4,  6,  9, 10, 11, 12, 13 /)

  INTEGER, PARAMETER, DIMENSION(2) :: MONITOR = (/ &
       6, 13 /)

  CHARACTER(LEN=15), PARAMETER, DIMENSION(1) :: SMASS = (/ &
     'N              ' /)

  CHARACTER(LEN=100), PARAMETER, DIMENSION(15) :: EQN_NAMES = (/ &
     '   O + O2 --> O3                                                                                    ', &
     '      NO2 --> O + NO                                                                                ', &
     '  NO + O3 --> NO2 + O2                                                                              ', &
     '       O3 --> O + O2                                                                                ', &
     '       O3 --> O1D + O2                                                                              ', &
     '  O1D + M --> O + M                                                                                 ', &
     'O1D + H2O --> 2 OH                                                                                  ', &
     '  CO + OH --> CO2 + HO2                                                                             ', &
     ' HO2 + NO --> OH + NO2                                                                              ', &
     ' OH + NO2 --> HNO3                                                                                  ', &
     '    2 HO2 --> H2O2                                                                                  ', &
     ' HO2 + O3 --> OH + 2 O2                                                                             ', &
     '     H2O2 --> 2 OH                                                                                  ', &
     '     H2O2 --> H2O2aq                                                                                ', &
     '     HNO3 --> HNO3aq                                                                                ' /)

! INLINED global variables

! End INLINED global variables


END MODULE ttropo_Monitor
