! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : my_strato_JacobianSP.f90
! Time                 : Sat Nov 19 20:06:28 2016
! Working directory    : /home/tomas/Downloads/kpp-2.2.3/test2
! Equation file        : my_strato.kpp
! Output root filename : my_strato
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE my_strato_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(19) :: LU_IROW = (/ &
       1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  3,  4, &
       4,  4,  4,  5,  5,  5,  5 /)

  INTEGER, PARAMETER, DIMENSION(19) :: LU_ICOL = (/ &
       1,  3,  1,  2,  3,  5,  1,  2,  3,  4,  5,  2, &
       3,  4,  5,  2,  3,  4,  5 /)

  INTEGER, PARAMETER, DIMENSION(6) :: LU_CROW = (/ &
       1,  3,  7, 12, 16, 20 /)

  INTEGER, PARAMETER, DIMENSION(6) :: LU_DIAG = (/ &
       1,  4,  9, 14, 19, 20 /)


END MODULE my_strato_JacobianSP

